'use client';

import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

type BriefPDFProps = {
  brief: string;
  brandName: string;
  brandTagline: string;
  accentColor: string;
  briefTypeName: string;
};

export function BriefPDF({
  brief,
  brandName,
  brandTagline,
  accentColor,
  briefTypeName,
}: BriefPDFProps) {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const sections = brief.split(/\n(?=[A-Z][A-Z\s&\/()]+:)/g);

  const styles = StyleSheet.create({
    page: {
      paddingTop: 40,
      paddingBottom: 60,
      paddingHorizontal: 44,
      fontFamily: 'Helvetica',
      fontSize: 10,
      color: '#1a1a1a',
      backgroundColor: '#ffffff',
    },
    headerBar: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: 5,
      backgroundColor: accentColor,
    },
    brandName: {
      fontSize: 20,
      fontFamily: 'Helvetica-Bold',
      color: '#1a1a1a',
      marginBottom: 2,
    },
    brandTagline: {
      fontSize: 9,
      color: '#888',
      letterSpacing: 1,
      marginBottom: 20,
    },
    metaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 24,
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: '#e5e5e5',
    },
    metaLabel: {
      fontSize: 7,
      fontFamily: 'Helvetica-Bold',
      letterSpacing: 1.5,
      color: '#aaa',
      marginBottom: 3,
    },
    metaValue: {
      fontSize: 11,
      fontFamily: 'Helvetica-Bold',
      color: '#333',
    },
    sectionBlock: {
      marginBottom: 14,
    },
    sectionHeader: {
      fontSize: 7,
      fontFamily: 'Helvetica-Bold',
      letterSpacing: 1.8,
      color: accentColor,
      marginBottom: 5,
    },
    sectionContent: {
      fontSize: 10,
      lineHeight: 1.65,
      color: '#333',
    },
    gapsBlock: {
      marginBottom: 14,
      paddingLeft: 10,
      borderLeftWidth: 2,
      borderLeftColor: accentColor,
    },
    plainText: {
      fontSize: 10,
      lineHeight: 1.65,
      color: '#333',
      marginBottom: 8,
    },
    footer: {
      position: 'absolute',
      bottom: 20,
      left: 44,
      right: 44,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: '#e5e5e5',
    },
    footerText: {
      fontSize: 7,
      color: '#bbb',
    },
    footerBar: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 5,
      backgroundColor: accentColor,
    },
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerBar} fixed />

        <Text style={styles.brandName}>{brandName}</Text>
        <Text style={styles.brandTagline}>{brandTagline.toUpperCase()}</Text>

        <View style={styles.metaRow}>
          <View>
            <Text style={styles.metaLabel}>BRIEF TYPE</Text>
            <Text style={styles.metaValue}>{briefTypeName}</Text>
          </View>
          <View>
            <Text style={styles.metaLabel}>GENERATED</Text>
            <Text style={styles.metaValue}>{date}</Text>
          </View>
        </View>

        {sections.map((section, i) => {
          const headerMatch = section.match(/^([A-Z][A-Z\s&\/()]+):([\s\S]*)/);
          if (headerMatch) {
            const header = headerMatch[1].trim();
            const content = headerMatch[2].trim();
            const isGaps = /^GAPS/.test(header);

            return (
              <View key={i} style={isGaps ? styles.gapsBlock : styles.sectionBlock} wrap={false}>
                <Text style={styles.sectionHeader}>{header}</Text>
                <Text style={styles.sectionContent}>{content}</Text>
              </View>
            );
          }

          if (!section.trim()) return null;
          return (
            <Text key={i} style={styles.plainText}>
              {section.trim()}
            </Text>
          );
        })}

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Generated by EPA \u2022 {brandName}</Text>
          <Text style={styles.footerText}>{date}</Text>
        </View>
        <View style={styles.footerBar} fixed />
      </Page>
    </Document>
  );
}
